version: '3.9'

services:

#  orng-auth:
#    hostname: ${AUTH_CONTAINER_HOST:orng-auth}
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    image: orng-auth:${APP_VERSION:-latest}
#    restart: always
#    env_file:
#      - .env


  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
    # Скрипт для инициализации, скорее всего для demo стенда
    #    volumes:
    #      - type: bind
    #        source: ./init.sql
    #        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db:
