version: '3.9'

services:

  orng-auth:
    image: bitmaximum/orng-auth:latest
    container_name: orng-auth
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/orng?currentSchema=orng_auth
      DB_USER: orng
      DB_PASS: orng
    depends_on:
      - database


  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres-db'
    restart: always
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5432:5432"

volumes:
  db:
