version: '3.9'

services:

  orng-auth:
    image: orng-auth:${APP_VERSION:-latest}
    build:
      context: .
    container_name: orng-auth
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database


  database:
    image: 'postgres:18-alpine'
    container_name: 'postgres-db'
    restart: always
    environment:
      - POSTGRES_USER=orng
      - POSTGRES_PASSWORD=orng
      - POSTGRES_DB=orng
    volumes:
      - db:/var/lib/postgresql/data postgres
    # Скрипт для инициализации, скорее всего для demo стенда
    #    volumes:
    #      - type: bind
    #        source: ./init.sql
    #        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db:
